server:
  port: 4242

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: asd321
    username: root
    url: jdbc:mysql://localhost:3306/usermanage?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update